### ISSUE TITLE
Switch Frequency Domain and Time/Spatial Domain

### ISSUE THREAD

**Issue by tknopp** [JuliaMath/NFFT.jl#101]
Until now we followed the mathematical notation of the NFFT3, which is the library I contributed to quite some time ago. In that definition the input signal of the NDFT is considered to be a frequency domain signal (equidistantly sampled) and the output signal is considered to be a time/spatial domain signal. However, that convention actually conflicts with the common DFT/FFT convention.

Some research in the literature reveals that [Fessler/Sutton: Nonuniform fast Fourier transforms using min-max interpolation] actually gets this right and defined the NDFT compatible to the DFT.

After much thinking about this I now plan to switch the definition to be compatible as well. This will not change any functionality but just
* the documentation.
* x and k will switch in the examples, i.e. k is now non-equidistantly sampled.

I am open to comments but assume/hope that @JeffFessler is in favor. My JuliaCon is already recorded with the old convention but should not count as an argument to stick with the old convention.

**Comment by JeffFessler** [comment]
I remember it took me an extra few minutes to figure this out when I first started using NFFT.jl, so yes I favor the switch.

My preference would be to use `n` rather than `x` for the uniformly sampled variable because (perhaps due to my early exposure to FORTRAN) `x` feels like a continuous variable whereas `n` feels like an integer, and having `-N/2 ≤ n < N/2-1` seems natural to me.  Maybe that's bike shedding though 😄 

No matter what you do, the user will always have to study the documentation because codes vary:
* 0 to N-1 vs -N/2 to N/2-1 (or even vs 1 to N)
* `k` might have units cycles/sample or radians/sample
* +/- i in the exponent

**Comment by tknopp** [comment]
Thanks for the feedback. Indeed when it comes to the naming of the variables there is indeed still some room for improvement. I see the point with `x` not being the perfect indexing variable. Right now `n` is used for the oversampled grid size but I may find something else for that.

> No matter what you do, the user will always have to study the documentation because codes vary

Totally agree. But still all my colleagues ask me why my NDFT is defined backwards to the DFT and this is now the chance to fix that.

**Comment by ahbarnett** [comment]
Looks like the project is progressing - and I like the performance page.

In NUFFT applications the NU points may be in physical or Fourier space, and the user has to figure that out by reading the mathematical definitions. There are a couple of conventions out there (could be summarized by NFFT vs MIRT/MRI vs CMCL/FINUFFT). This affects names like "adjoint" vs "type 1", whether there's a 2pi (affecting domain of periodicity), +-i, k_j vs x_j, etc, as Jeff says. The important thing is to stick to a widely-used one and not invent a new one. No notation can match the DFT.  We in FINUFFT used x_j, and then k etc for integer frequency index (and removed an ugly normalization choice in CMCL). The advantage of that is when you go to type 3, the k simply change from integer to NU points k_i.
But your decision to use k_j for the NU points is ok. x certainly shouldn't be used for an integer!

At the moment your definitions
https://juliamath.github.io/NFFT.jl/dev/background/#Mathematical-Background
are confusing and have typos: bold-k and italic-k and bold-n seem to be mixed up even in paragraph 1 and the 1st formula, right?

I suggest you write the math in a more tutorial fashion, not jumping into the abstract arbitrary-dim case, but starting with 1d, and including intuitive descriptions. Happy to contribute/feedback if you let me know when you're ready.

You may also want to wrap ducc.nufft which seems to be up to 2x faster than FINUFFT:
https://gitlab.mpcdf.mpg.de/mtr/ducc/
Would need wrapping C++.

Meanwhile we are working on speeding up FINUFFT.  Best wishes, Alex

PS if you want to see some poor conventions & performance, check out MathWorks nufft in recent MATLAB versions :)

**Comment by tknopp** [comment]
> At the moment your definitions
https://juliamath.github.io/NFFT.jl/dev/background/#Mathematical-Background
are confusing and have typos: bold-k and italic-k and bold-n seem to be mixed up even in paragraph 1 and the 1st formula, right

Thanks, this is work in progress. I needed to fix all definitions in the source code what was quite a challenge. Will fix that.

> You may also want to wrap ducc.nufft which seems to be up to 2x faster than FINUFFT

In 3D? I can't really believe that since both FINUFFT and NFFT.jl converge to similar performance ("bare metal").

**Comment by tknopp** [comment]
I am closing this specific issue since decisions have been made and we made a big renaming within the package and the documentation. @migrosser has also fixed docu issues. For further enhancements I suggest to just directly make a pull request, which can be done by changing the files here: https://github.com/JuliaMath/NFFT.jl/tree/master/docs/src

Thanks again for the feedback!
