### ISSUE TITLE
BoundsError 

### ISSUE THREAD

**Issue by JakobAsslaender** [JuliaMath/NFFT.jl#106]
Hi, 

I get the following error message:

```
ERROR: BoundsError: attempt to access 655361-element Vector{Float32} at index [655362]
Stacktrace:

getindex at ./array.jl

macro expansion at ~/.julia/packages/NFFT/BSQNX/src/precomputation.jl

shiftedWindowEntries(winLin::Vector{Float32}, idx::Float32, scale::Int64, d::Int64, L::Val{10}) at ~/.julia/packages/NFFT/BSQNX/src/precomputation.jl

macro expansion at ~/.julia/packages/NFFT/BSQNX/src/precomputation.jl

precomputeOneNode(winLin::Vector{Float32}, winPoly::Nothing, k::Matrix{Float32}, Ñ::Tuple{Int64, Int64, Int64}, m::Int64, σ::Float32, scale::Int64, j::Int64, d::Int64, L::Val{10}, LUTSize::Int64) at ~/.julia/packages/NFFT/BSQNX/src/precomputation.jl

macro expansion at ~/.julia/packages/NFFT/BSQNX/src/convolution.jl

__convolve_transpose_nonblocking!(p::NFFTPlan{Float32, 3, 1}, fHat::Vector{ComplexF32}, g::Array{ComplexF32, 3}, L::Val{10}, winPoly::Nothing, scale::Int64, j::Int64) at ~/.julia/packages/NFFT/BSQNX/src/convolution.jl

macro expansion at ~/.julia/packages/NFFT/BSQNX/src/convolution.jl

macro expansion at ./simdloop.jl

_convolve_transpose_nonblocking!(p::NFFTPlan{Float32, 3, 1}, fHat::Vector{ComplexF32}, g::Array{ComplexF32, 3}, L::Val{10}, winPoly::Nothing) at ~/.julia/packages/NFFT/BSQNX/src/convolution.jl

convolve_transpose_nonblocking!(p::NFFTPlan{Float32, 3, 1}, fHat::Vector{ComplexF32}, g::Array{ComplexF32, 3}) at ~/.julia/packages/NFFT/BSQNX/src/convolution.jl

convolve_transpose! at ~/.julia/packages/NFFT/BSQNX/src/convolution.jl

macro expansion at ./timing.jl

mul!(f::Array{ComplexF32, 3}, pl::LinearAlgebra.Adjoint{ComplexF32, NFFTPlan{Float32, 3, 1}}, fHat::Vector{ComplexF32}; verbose::Bool, timing::Nothing) at ~/.julia/packages/NFFT/BSQNX/src/implementation.jl

mul!(f::Array{ComplexF32, 3}, pl::LinearAlgebra.Adjoint{ComplexF32, NFFTPlan{Float32, 3, 1}}, fHat::Vector{ComplexF32}) at ~/.julia/packages/NFFT/BSQNX/src/implementation.jl

top-level scope at Untitled-2
```

when running this MWE:
```
using FFTW
using NFFT

T = Float32
Nr = 320
Nx = 160
Ny = 150
Nz = 120
img_shape_os = (2Nx, 2Ny, 2Nz)
λ = Array{Complex{T}}(undef, img_shape_os)

fftplan = plan_fft(Array{Complex{T}}(undef, img_shape_os); flags = FFTW.MEASURE)

trj = Matrix{T}(undef, 3, 2)
nfftplan = plan_nfft(trj, img_shape_os; precompute = LINEAR, blocking = false, fftflags = FFTW.ESTIMATE)

trj[1,:] .= 0
trj[2,:] .= 0
trj[3,:] .= 0.008333332 # works fine

nfftplan = plan_nfft(trj, img_shape_os; precompute = LINEAR, blocking = false, fftflags = FFTW.ESTIMATE)
mul!(λ, adjoint(nfftplan), ones(Complex{T}, size(trj,2)))

##
trj[3,:] .= 0.008333333 # throws error
nfftplan = plan_nfft(trj, img_shape_os; precompute = LINEAR, blocking = false, fftflags = FFTW.ESTIMATE)
mul!(λ, adjoint(nfftplan), ones(Complex{T}, size(trj,2)))

##
trj[3,:] .= 0.008333334 # works fine
nfftplan = plan_nfft(trj, img_shape_os; precompute = LINEAR, blocking = false, fftflags = FFTW.ESTIMATE)
mul!(λ, adjoint(nfftplan), ones(Complex{T}, size(trj,2)))
```

Not that this error does not occur with `T=Float64` or with several other `Nz` values, e.g., with `Nz = 122`. Naturally, it also does not occur with `precompute = POLYNOMIAL` either. I am guessing that this must some weird rounding issue? I wrote some outputs and it turns out that in this line:

https://github.com/JuliaMath/NFFT.jl/blob/5f3dc6cd42143f372096f2853288b29dffdcb585/src/precomputation.jl#L202

`idxInt1` is exactly the bound and `idxInt2` is out of bound by 1. The function inputs of `shiftedWindowEntries` that cause the error are
```
[ Info: idx = 655360.0
[ Info: scale = 131072
[ Info: d = 3
[ Info: L = Val{10}()
```
I assume that `idx = 655360.0` being exactly an integer might be the issue here? In this case `α == 0` and one could write
```
if α == 0
        (winLin[idxInt1])
else
        (winLin[idxInt1] + α * (winLin[idxInt2] - winLin[idxInt1]))
end
```
However, a quick test revealed a roughly 20% performance penalty. I am sure there are better ways to fix this, but this meta-code is way to abstract for me to understand, so I hope you, @tknopp can help fix this. ;)

Mentioning @andrewwmao to keep him in the loop about this issue.

**Comment by JakobAsslaender** [comment]
Out of curiosity: What is the difference between `idxL = floor(Int,idx)` and `idxInt = Int(idxL)`? Aren't they both `Int`?

**Comment by tknopp** [comment]
Thanks for the report and the very helpful analysis! I will have a look and try figuring out where my math got wrong.

In the mean time: Could you just switch to `POLYNOMIAL`, which is the default nowadays? It will be faster anyway. Furthermore you could set `blocking = true` which is usually faster even in the single-threaded case.

> Out of curiosity: What is the difference between idxL = floor(Int,idx) and idxInt = Int(idxL)? Aren't they both Int?

Agree, that code looks odd. `idxL` and `idxInt` are always the same and we need to remove one.

**Comment by JakobAsslaender** [comment]
You are right, these two are about the same...

**Comment by tknopp** [comment]
I committed a quick fix in https://github.com/JuliaMath/NFFT.jl/commit/2fe481ee2fa3911eb61a58cc5555809fb705e3f7. Would be great if you could have a look if this also leads to a performance regression. I actually don't think so. In the mean time I try a different fix.

**Comment by JakobAsslaender** [comment]
Both seem to work, and the better fix is definitely the faster fix ;). In fact, it is faster than prior to the fix!

**Comment by tknopp** [comment]
bug fix release is triggered.
