### ISSUE TITLE
NFFTTools.sdc doesn't work with 2D CuNFFT plan

### ISSUE THREAD

**Issue by marius311** [JuliaMath/NFFT.jl#110]
With CuNFFT v0.3.4 and NFFTTools v0.2.5 I get this error for a 2D NFFT:

```julia
sdc(plan, iters=2)

CuNFFT.CuNFFTPlan{Float32, 2} must implement convolve_transpose!

Stacktrace:
 [1] error(::Type, ::String, ::Symbol)
   @ Base ./error.jl:44
 [2] convolve_transpose!(p::CuNFFT.CuNFFTPlan{Float32, 2}, fHat::Vector{ComplexF32}, g::CuArray{ComplexF32, 2, CUDA.Mem.DeviceBuffer})
   @ AbstractNFFTs ./none:0
 [3] sdc(p::CuNFFT.CuNFFTPlan{Float32, 2}; iters::Int64)
   @ NFFTTools ~/.julia/packages/NFFTTools/FB6T2/src/samplingDensity.jl:11
 [4] top-level scope
   @ In[366]:1
```

Would be useful to have this working to avoid having to switch back to CPU. (Fwiw I haven't checked with 1D, so not sure if that works, or if this was just never implemented)

**Comment by tknopp** [comment]
Yes, it is not unexpected that this does not work :-)
Are you really using CuNFFT (cool!) or were you toying around and found that this does not work. The answer has an impact on the priority of fixing this...

**Comment by marius311** [comment]
CuNFFT has turned out to be a really critical piece of some Cosmic Microwave Background analysis we're doing to interpolate maps between different projections on the sphere, specifically CuNFFT (not NFFT) since the whole thing really needs to be on GPU to be anywhere near fast enough (see eg [this](https://github.com/marius311/CMBLensing.jl/blob/134c64b6edc6fbba8904884ceb8b4a4ddacc43cf/src/proj_healpix.jl#L274-L284) and [this](https://twitter.com/cosmic_mar/status/1593707824088956929)). So huge thanks for this package. 

Fwiw I can't say `sdc` is totally critical for right now though, since I have a decent empirical workaround. Basically my particular case I know the entries in the "W" matrix scale like sin(theta) due to the spherical geometry, although I haven't been able to figure out an overall normalization. But I can get the normalization with a couple NFFT evals since after the scaling W is proportional to identity. Would be more automatic to have `sdc`, also to check that scaling is actually what I think it is.

**Comment by tknopp** [comment]
I gave this a go and `sdc` should now work with `CuNFFT`. You need to update `CuNNFT` and `NFFTTools`.

**Comment by marius311** [comment]
Awesome, thank you, testing it out now.
