### ISSUE TITLE
Use of NFFT

### ISSUE THREAD

**Issue by dashingdiggi** [JuliaMath/NFFT.jl#111]
Dear Sir,

I  recently started working on NFFT.  I Have a really basic question about this package, please excuse me for that.
I have irregularly sampled data in the time domain. Can I compute its spectrum using NFFT.jl? As I can see in the algorithm, NFFT requires data to be sampled regularly in any one of the domains. I really appreciate any help you can provide. 

Thank you.

**Comment by JeffFessler** [comment]
That question is not so basic actually.  I have some comments about it here:
https://github.com/JeffFessler/mirt/blob/main/nufft/example_nufft1_reverse.m
I would recommend using density compensation if you want to pursue this.

**Comment by JeffFessler** [comment]
You might want to take a look at this paper:
https://arxiv.org/abs/2302.00414

**Comment by tknopp** [comment]
I think we can close this. Further user questions can be asked in our discussion forum: https://github.com/JuliaMath/NFFT.jl/discussions
