### ISSUE TITLE
Cite NFFT.jl

### ISSUE THREAD

**Issue by roflmaostc** [JuliaMath/NFFT.jl#68]
Hi!

We would like to cite this package in a scientific work. Any preferences how to do that?

Best,

Felix

**Comment by tknopp** [comment]
Panic mode: This puts me under pressure writing a short paper ASAP. Whats your timeline? 

Background: I actually wanted to write a longer software paper but probably best would be to bring out a JOSS article now so that people have something to cite.

**Comment by roflmaostc** [comment]
I guess like ~4 weeks?

**Comment by tknopp** [comment]
4 weeks until submission / revision / acceptance / publication?

**Comment by roflmaostc** [comment]
Until submission

**Comment by tknopp** [comment]
Thanks, that gives me a timeline.

And note that I am extremely thrilled that this package is useful for others. That gives strong motivation pushing it forward.

**Comment by tknopp** [comment]
@roflmaostc: We now have a preprint available on NFFT.jl. Please cite this. The paper is submitted to a journal as well and once it is accepted I will add more appropriately citation information to the documentation.

**Comment by tknopp** [comment]
I added information on the preprint in the documentation and therefore close this issue.

**Comment by roflmaostc** [comment]
Thanks and Congrats!
