### ISSUE TITLE
Crashing Julia

### ISSUE THREAD

**Issue by RainerHeintzmann** [JuliaMath/NFFT.jl#83]
Using the example code, but providing ranges that go beyond the `-0.5:0.5` range lead to crashes:
```julia
    M, N = 8, 16
    x = range(-40.0, stop=10.2, length=M)  # nodes which are outside the normally allowed area
    fHat = randn(ComplexF64,M)           # data to be transformed
    p = plan_nfft(x, N)                  # create plan. m and σ are optional parameters
    f2 = adjoint(p) * fHat                # calculate adjoint NFFT
    g = p * f2 
```
sometimes crashes the whole REPL. After the line `p = plan_nfft(x, N) ` one can see the following error:
```julia
RROR: LoadError: UndefRefError: access to undefined reference
Stacktrace:
  [1] getindex
    @ .\array.jl:861 [inlined]
  [2] macro expansion
    @ C:\Users\pi96doc\.julia\packages\NFFT\2cFLT\src\precomputation.jl:336 [inlined]
  [3] macro expansion
    @ C:\Users\pi96doc\.julia\packages\NFFT\2cFLT\src\utils.jl:10 [inlined]
  [4] _precomputeBlocks(x::Matrix{Float64}, n::Tuple{Int64}, m::Int64, LUTSize::Int64)
    @ NFFT C:\Users\pi96doc\.julia\packages\NFFT\2cFLT\src\precomputation.jl:334
  [5] precomputeBlocks(x::Matrix{Float64}, n::Tuple{Int64}, params::NFFTParams{Float64}, calcBlocks::Bool)
    @ NFFT C:\Users\pi96doc\.julia\packages\NFFT\2cFLT\src\precomputation.jl:288
  [6] NFFTPlan(x::Matrix{Float64}, N::Tuple{Int64}; dims::UnitRange{Int64}, fftflags::Nothing, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ NFFT C:\Users\pi96doc\.julia\packages\NFFT\2cFLT\src\implementation.jl:88
  [7] NFFTPlan
    @ C:\Users\pi96doc\.julia\packages\NFFT\2cFLT\src\implementation.jl:79 [inlined]
  [8] macro expansion
    @ C:\Users\pi96doc\.julia\packages\NFFT\2cFLT\src\NFFT.jl:45 [inlined]
  [9] macro expansion
    @ .\timing.jl:299 [inlined]
 [10] #plan_nfft#100
    @ C:\Users\pi96doc\.julia\packages\NFFT\2cFLT\src\NFFT.jl:44 [inlined]
 [11] plan_nfft(::Type{Array}, ::Matrix{Float64}, ::Tuple{Int64})
    @ NFFT C:\Users\pi96doc\.julia\packages\NFFT\2cFLT\src\NFFT.jl:44
 [12] plan_nfft(::Type, ::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, ::Int64; kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ AbstractNFFTs C:\Users\pi96doc\.julia\packages\AbstractNFFTs\MKWwX\src\derived.jl:16
 [13] plan_nfft(::Type, ::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, ::Int64)
    @ AbstractNFFTs C:\Users\pi96doc\.julia\packages\AbstractNFFTs\MKWwX\src\derived.jl:16
 [14] plan_nfft(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, ::Int64; kargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ AbstractNFFTs C:\Users\pi96doc\.julia\packages\AbstractNFFTs\MKWwX\src\derived.jl:8
 [15] plan_nfft(::StepRangeLen{Float64, Base.TwicePrecision{Float64}, Base.TwicePrecision{Float64}, Int64}, ::Int64)
    @ AbstractNFFTs C:\Users\pi96doc\.julia\packages\AbstractNFFTs\MKWwX\src\derived.jl:8
 [16] top-level scope
    @ c:\Users\pi96doc\Nextcloud-Uni\Julia\Development\resample_czt.jl:408
in expression starting at c:\Users\pi96doc\Nextcloud-Uni\Julia\Development\resample_czt.jl:408
```
running then the same line again causes the crash of the REPL.
Similar things also seem to happen accessing frequencies which are just a little bit out of the design range, but one then sees also less predictable errors (dark pixels in random places etc.).

**Comment by tknopp** [comment]
That is expected. We disabled all bounds checks to maximize speed an be on par with the C/C++ libraries.

(But yes we should address it. I will add a range check during plan construction. Thanks for the report.)

**Comment by RainerHeintzmann** [comment]
A range check during plan construction would be great. What exactly are the ranges and is there a way to calculate outside these ranges, or would such values automatically be assigned to zero? I guess a normal FFT assumes cyclic wrap-around if addressed outside the range. Does this make sense for NFFTs or is this a bad idea?

**Comment by RainerHeintzmann** [comment]
Thanks a lot. I will implement a clipping on my side and retrospectively replace the clipped frequencies with a padding value. Hope that this is a sensible option. I also decided to implement the ability of supplying a function rather than the values calling the regular-array version which I am implementing in FourierTools.jl.
Btw. Did someone implement a Fourier-Mellin transform based on your toolbox? Sounds like a straight-forward thing to try.

**Comment by JeffFessler** [comment]
I had included a range check in my wrapper long ago because I too had users (including myself) who would get bad values when trying to go outside the feasible range.
I have an option that lets the user over-ride the check (I forget why) but I doubt if anyone uses it.
https://github.com/JeffFessler/MIRT.jl/blob/8fc756c5747a6e21d65e95586495cc9411894875/src/nufft/nufft.jl#L87
https://github.com/JeffFessler/MIRT.jl/blob/8fc756c5747a6e21d65e95586495cc9411894875/src/nufft/nufft.jl#L88

**Comment by tknopp** [comment]
> Did someone implement a Fourier-Mellin transform based on your toolbox? Sounds like a straight-forward thing to try.

Not that I am aware but I have to admit that I have no experience with Fourier-Mellin transform. Is it common knowledge that it can be calculated via N(u)FFT? So I would be interested if that could be a field of research or if its "just" implementation. In any ways I think this should go into a dedicated package `FourierMellinTransform.jl` or something like this.

**Comment by RainerHeintzmann** [comment]
Not sure if this is typically done via NFFTs. But should be.
If it isn't its certainly worth a paper...
