### ISSUE TITLE
Error when testing NFFT

### ISSUE THREAD

**Issue by aTrotier** [JuliaMath/NFFT.jl#84]
I was trying to test the latest version of MRIReco and it fails.

It is related to the NFFT package where the test also failed :
```julia
@ Transducers ~/.julia/packages/Transducers/CnpYX/src/reduce.jl:150
[19] (::Transducers.var"#165#166"{Transducers.BottomRF{Transducers.AdHocRF{NFFT.var"##oninit_function#319#92", typeof(identity), InitialValues.AdjoinIdentity{NFFT.var"##reducing_function#320#93"{2, Matrix{Float64}, Tuple{Int64, Int64}, Matrix{Vector{Int64}}, Tuple{Int64, Int64}}}, typeof(identity), typeof(identity), NFFT.var"##combine_function#321#95"}}, Transducers.InitOf{Transducers.DefaultInitOf}, Transducers.NoopDACContext, Transducers.SizedReducible{UnitRange{Int64}, Int64}})()
@ Transducers ./threadingconstructs.jl:169
Test Summary: | Pass  Error  Total
Constructors  |   17      1     18
ERROR: LoadError: LoadError: Some tests did not pass: 17 passed, 0 failed, 1 errored, 0 broken.
in expression starting at /Users/aurelien/.julia/packages/NFFT/xpKXe/test/constructors.jl:1
in expression starting at /Users/aurelien/.julia/packages/NFFT/xpKXe/test/runtests.jl:13
ERROR: Package NFFT errored during testing
```

Any idea ?

**Comment by tknopp** [comment]
Since the tests pass on Github actions and locally it is not really clear to me why that errors. I would say there is something wrong with your packages? The error comes from [FLoops.jl](https://github.com/JuliaFolds/FLoops.jl), which we use for multi-threading.

I suggest that you update your packages and then test again in a fresh Julia session. Best is to
- startup Julia
- ] activate --temp
- ] add NFFT
- ] test NFFT
- ] add MRIReco
- ] test MRIReco

**Comment by aTrotier** [comment]
Thanks. I found the issue.

If I launch julia with multiple threads `julia --thread 4` then I get an error (I tried for both thread 2/4).
Is it tested in Github actions ?

**Comment by aTrotier** [comment]
I tried on my server and it seems to work with multiple threads... 
Maybe it is only something happening on my mac.

**Comment by tknopp** [comment]
Wow, we had a serious bug in in the multi-threading code. I have a hot fix and now test on CI with multiple threads.

**Comment by aTrotier** [comment]
I tried and it seems to works now 👍
