### ISSUE TITLE
Crash with NaNs in the coordinates

### ISSUE THREAD

**Issue by RainerHeintzmann** [JuliaMath/NFFT.jl#86]
Thanks for solving the crash with out-of-bound problems.
Yet this is not perfectly solved yet as NaN still crash the Julia system:
```julia
using NFFT
M, N = 8, 16
x = collect(range(-0.5, stop=0.5, length=M))  # nodes which are outside the normally allowed area
x[4] = NaN
fHat = randn(ComplexF64,M)           # data to be transformed
p = plan_nfft(x, N)                  # create plan. m and σ are optional parameters
f2 = adjoint(p) * fHat                # calculate adjoint NFFT
g = p * f2 
```
I think `NaN`x in the data will only cause arrays of `NaN`x which is fine, but the coordinates are still fatal.

**Comment by RainerHeintzmann** [comment]
Great! Thanks. Is there already a new release?

**Comment by tknopp** [comment]
Soon: https://github.com/JuliaRegistries/General/pull/54459
